using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CarParts.Data.Migrations
{
    public partial class ChangedSeedingCarsIds : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 207);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 208);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 209);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 210);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 211);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 212);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 213);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 214);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 215);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 216);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 217);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 218);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 219);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 220);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 221);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 222);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 223);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 224);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 225);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 226);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 227);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 228);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 229);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 230);

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "asd4f072-ecca-43c9-ab26-c060c6f364e4",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "88575ad3-7b9c-49af-b34d-1a5d00dc68dd", "AQAAAAEAACcQAAAAEMFaRIejDJ0HtV9DRgFPBQvmRpzxTOGE5hCTvwM5NqOC86KzunO6NHZ4q9qQzhrqWA==", "ff9d086d-f1e8-4df6-bc31-b42c6a60bc14" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "bcb4f072-ecca-43c9-ab26-c060c6f364e4",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "c5ce0157-4468-4c02-82a6-ac330a649cdc", "AQAAAAEAACcQAAAAEH9ipkKzfCuM6g0noMPPro+53bR/4c1Unw+AjcyFBuuqzZ2VCRb/fRnBDkaGACMUBA==", "8ccb9562-73e4-4977-9ced-7c493b84441c" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "qwe4f072-ecca-43c9-ab26-c060c6f364e4",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "a9081a77-6e3e-435f-b5db-e89f85351f39", "AQAAAAEAACcQAAAAELAM/MljX4yCXqbgoBoPNJ6IE80zW6FO9HBpeKC3W1xntwqMuMK7v3lWB1tvJxoWdg==", "36f1c9ce-a79a-4a88-ae77-f4b4d5435116" });

            migrationBuilder.InsertData(
                table: "Cars",
                columns: new[] { "CarId", "Acceleration", "CategoryId", "Color", "DealerId", "Description", "EngineSize", "FuelConsumption", "FuelTypeId", "Horsepower", "ImageUrl", "Make", "Model", "Price", "RentPrice", "RentalEndDate", "RentalStartDate", "RenterId", "TopSpeed", "Torque", "TransmissionId", "Weight", "Year" },
                values: new object[,]
                {
                    { 236, 4.9000000000000004, 1, "Black", 14, "The Mercedes-Benz S-Class (W223), a pinnacle of luxury and engineering excellence, continues its legacy in the year 2022. Renowned for its opulent features, cutting-edge technology, and refined performance, the S-Class remains a symbol of sophistication and prestige. The exterior design of the S-Class (W223) strikes a balance between timeless elegance and modern aesthetics. The body lines exude a sense of fluidity and strength, while the meticulously crafted details showcase the brand's commitment to perfection. Inside, the cabin offers an oasis of comfort and luxury. Premium materials, exquisite craftsmanship, and advanced features create an ambiance that indulges the senses. Mercedes-Benz's latest innovations are seamlessly integrated into the S-Class. The state-of-the-art MBUX infotainment system greets occupants with intuitive controls, voice commands, and a futuristic digital cockpit. Augmented reality navigation, AI-powered predictive functions, and customizable displays elevate the driving experience. Under the hood, the S-Class offers an array of potent powertrains, catering to diverse preferences. From refined gasoline and diesel engines to electrified options, each variant delivers a harmonious blend of power and efficiency. The advanced suspension system ensures a smooth and controlled ride, even on challenging road surfaces. Mercedes-Benz's commitment to safety is exemplified by the S-Class (W223). The vehicle incorporates an array of advanced driver assistance systems, including adaptive cruise control, lane-keeping assist, automatic emergency braking, and more. These features work together to enhance driver confidence and mitigate potential risks. The S-Class is renowned for introducing groundbreaking innovations, and the W223 is no exception. It boasts technologies such as E-Active Body Control, which uses cameras to scan the road and adjust the suspension accordingly, providing unparalleled comfort and stability. In conclusion, the Mercedes-Benz S-Class (W223) exemplifies the brand's dedication to luxury, technology, and performance. As a flagship model, it continues to set the standard for the automotive industry, redefining what it means to travel in style and comfort. With its timeless design and cutting-edge features, the S-Class remains an icon of automotive excellence in the year 2022.", 2999.0, 0.69999999999999996, 4, 365.0, "https://www.auto-data.net/images/f94/Mercedes-Benz-S-class-W223.jpg", "Mercedes-Benz", "S-Class (W223)", 175000.0, 700.0, null, null, null, 250.0, 500.0, 1, 2345.0, 2022 },
                    { 237, 12.9, 3, "black", 14, "The VW Golf 5, launched in 2004, is a part of Volkswagen's renowned Golf lineup. It blends practicality, reliability, and driving enjoyment seamlessly. With a design that balances aesthetics and modern simplicity, the Golf 5's compact dimensions offer style without sacrificing functionality. Inside, the cabin emphasizes user-friendly controls, comfortable seating, and ample cargo space. Under the hood, the Golf 5 presents a range of engine options, each delivering a mix of efficiency and performance. Responsive steering and a well-tuned suspension contribute to a confident driving experience. While not equipped with the latest technology, the Golf 5's interior provides essential comforts, reflecting Volkswagen's commitment to quality. In terms of safety, the Golf 5 incorporates airbags, anti-lock brakes, and stability control for occupant protection. As a significant iteration in the Golf lineup, the Golf 5 upholds the model's reputation for reliability and practicality, appealing to drivers seeking an affordable and dependable option. In summary, the 2004 VW Golf 5 remains a symbol of reliability and practicality within the compact car segment. Its enduring design, balanced performance, and comfort continue to exemplify Volkswagen's dedication to meeting diverse driver needs.", 1896.0, 6.5, 1, 90.0, "https://www.auto-data.net/images/f118/Volkswagen-Golf-V.jpg", "VW", "Golf 5", 6200.0, 40.0, null, null, null, 176.0, 210.0, 1, 1285.0, 2004 },
                    { 238, 10.1, 3, "Red", 21, "The Skoda Fabia III, introduced in 2018 by Skoda, embodies practicality, efficiency, and modern design in the compact car segment. With its sleek exterior and contemporary lines, the Fabia III boasts a design that merges aesthetics with functionality. The compact dimensions make it maneuverable in urban environments while offering ample interior space for passengers and cargo. Under the hood, the Fabia III offers a range of efficient engines, catering to both city commuting and longer journeys. Its balanced performance strikes a chord between fuel efficiency and driving enjoyment. The cabin of the Fabia III reflects Skoda's commitment to user-centered design. The interior space is intelligently organized, providing ergonomic seating and intuitive controls. Modern connectivity features ensure a convenient driving experience. In terms of safety, the Fabia III is equipped with standard airbags, anti-lock brakes, stability control, and more. While not the most advanced in terms of safety tech, it delivers a reassuring level of protection. As a part of Skoda's lineup, the Fabia III aligns with the brand's reputation for reliability and practicality. It's an ideal choice for drivers seeking a compact car that effortlessly combines style and functionality. In conclusion, the 2018 Skoda Fabia III stands as a testament to Skoda's commitment to producing compact cars that excel in practicality and efficiency. With its modern design, well-organized interior, and balanced performance, the Fabia III remains a relevant choice for drivers looking for a reliable and stylish urban companion.", 2993.0, 5.5999999999999996, 2, 110.0, "https://www.auto-data.net/images/f76/Skoda-Fabia-III-facelift-2018.jpg", "Skoda", "Fabia III", 24000.0, 130.0, null, null, null, 195.0, 200.0, 2, 1957.0, 2018 },
                    { 239, 6.7999999999999998, 4, "Dark blue", 14, "The Lexus RX IV, introduced in 2016 by Lexus, is a luxury SUV that blends sophistication, advanced technology, and comfort in a seamless package. Characterized by its bold and distinctive design, the RX IV commands attention on the road. The sharp lines and signature Lexus spindle grille contribute to its upscale presence, while the attention to detail showcases the brand's commitment to craftsmanship. Inside the RX IV, the cabin offers a sanctuary of luxury and modernity. High-quality materials, exquisite finishes, and meticulously crafted details create an ambiance that indulges the senses. The intuitive layout and user-friendly controls contribute to an effortless driving experience. Under the hood, the RX IV offers a range of powerful and efficient engine options, delivering both performance and fuel economy. The advanced suspension system ensures a smooth and composed ride, making it well-suited for both city driving and long journeys. Lexus is synonymous with cutting-edge technology, and the RX IV is no exception. It incorporates a suite of advanced features, including a user-friendly infotainment system, driver assistance technologies, and a premium sound system, elevating the driving experience to new heights. In terms of safety, the RX IV is equipped with a comprehensive set of features, including adaptive cruise control, lane departure warning, automatic emergency braking, and more. These systems work in harmony to enhance driver confidence and mitigate potential risks. As a flagship SUV in Lexus's lineup, the RX IV exemplifies the brand's dedication to luxury and innovation. Its combination of bold design, refined interior, and advanced technology positions it as a compelling choice in the luxury SUV segment. In conclusion, the 2016 Lexus RX IV is a testament to Lexus's pursuit of excellence in luxury and performance. With its distinctive design, opulent interior, and state-of-the-art technology, the RX IV continues to capture the essence of modern luxury and remains a symbol of Lexus's commitment to elevating the driving experience.", 3456.0, 11.699999999999999, 2, 290.0, "https://www.auto-data.net/images/f28/file9510003.jpg", "Lexus", "RX IV", 85000.0, 220.0, null, null, null, 200.0, 363.0, 1, 2025.0, 2016 },
                    { 240, 9.5, 1, "White", 14, "The Volvo S40 II, introduced in 2011 by Volvo, represents a harmonious blend of Scandinavian design, safety innovation, and driving dynamics in a compact sedan package. The S40 II's exterior design exudes a distinctive blend of elegance and modernity. Clean lines and a sleek profile capture Volvo's commitment to minimalist aesthetics while conveying a sense of purposeful movement. Inside, the cabin of the S40 II offers a comfortable and intuitive environment. High-quality materials and meticulous attention to detail create an atmosphere that prioritizes both driver and passenger comfort. The user-friendly controls and ergonomic layout contribute to an enjoyable driving experience. Under the hood, the S40 II presents a range of efficient and capable engine options, delivering a balance between performance and fuel economy. The sedan's well-tuned suspension system provides a composed and engaging ride, whether navigating city streets or cruising on the highway. Volvo's reputation for safety innovation shines in the S40 II. The sedan is equipped with a comprehensive set of safety features, including advanced airbag systems, stability control, and Volvo's City Safety system, which can help prevent or mitigate collisions at low speeds. While the S40 II might not offer the most cutting-edge infotainment features, it does provide essential connectivity and entertainment options to enhance the driving experience. As part of Volvo's lineup, the S40 II embodies the brand's commitment to safety and quality. It's a compelling choice for drivers seeking a compact sedan that combines style, comfort, and advanced safety features. In summary, the 2011 Volvo S40 II remains a testament to Volvo's legacy of designing vehicles that prioritize safety, comfort, and Scandinavian aesthetics. With its elegant design, well-appointed interior, and comprehensive safety features, the S40 II continues to reflect Volvo's dedication to engineering vehicles that enhance both the driving experience and occupant well-being.", 1999.0, 10.800000000000001, 2, 145.0, "https://www.auto-data.net/images/f88/Volvo-S40-II-facelift-2007.jpg", "Volvo", "S40 II", 4800.0, 75.0, null, null, null, 200.0, 185.0, 2, 1370.0, 2011 },
                    { 241, 10.699999999999999, 5, "Red", 21, "The Kia Optima IV, introduced in 2018, is a midsize sedan that showcases Kia's commitment to style, technology, and value. With its modern exterior design, the Optima IV captures attention on the road. Sleek lines and a bold front grille create an assertive presence, while the attention to aerodynamics contributes to its efficiency. Inside the Optima IV, the cabin offers a blend of comfort and technology. High-quality materials and well-crafted surfaces create an inviting atmosphere. The intuitive infotainment system provides connectivity and entertainment features that enhance the driving experience. Under the hood, the Optima IV offers a range of engine options, catering to different preferences for performance and fuel efficiency. The sedan's well-balanced suspension and responsive steering contribute to a confident and enjoyable driving dynamic. In terms of safety, the Optima IV is equipped with a suite of features, including adaptive cruise control, automatic emergency braking, lane departure warning, and more. These features work together to enhance driver confidence and mitigate potential risks. As a part of Kia's lineup, the Optima IV represents the brand's commitment to delivering value without compromising on style and technology. It's a practical choice for drivers seeking a midsize sedan that offers a combination of comfort, performance, and safety. In conclusion, the 2018 Kia Optima IV reflects Kia's dedication to providing a well-rounded midsize sedan. With its modern design, comfortable interior, and advanced safety and technology features, the Optima IV remains a relevant choice for drivers who prioritize style and practicality in their daily commute.", 2993.0, 10.1, 2, 163.0, "https://www.auto-data.net/images/f56/Kia-Optima-IV-Sportswagon-facelift-2018.jpg", "Kia", "Optima IV", 3900.0, 360.0, null, null, null, 205.0, 196.0, 1, 1625.0, 2018 },
                    { 242, 6.4000000000000004, 1, "Black", 14, "The BMW E60, introduced in 2010, is a representation of BMW's commitment to luxury, performance, and driving pleasure in the midsize sedan category. With its iconic design, the E60 carries BMW's distinctive styling cues. The elegant yet dynamic lines of the exterior showcase a timeless aesthetic that blends sophistication with athleticism. Inside, the cabin of the E60 offers a driver-focused environment. High-quality materials, precision craftsmanship, and ergonomic design create a space that exudes luxury and comfort. The intuitive controls and advanced infotainment system contribute to an engaging driving experience. Under the hood, the E60 offers a range of powerful engine options, each delivering the performance and refinement expected from a BMW. The sedan's responsive handling and well-tuned suspension system provide a dynamic driving experience that balances comfort and sportiness. Safety features in the E60 include airbags, stability control, and advanced braking systems, which contribute to occupant protection and peace of mind while on the road. As part of BMW's lineup, the E60 upholds the brand's legacy of engineering excellence and driving dynamics. It's an appealing choice for drivers who seek a midsize sedan that offers a blend of luxury, performance, and prestige. In summary, the 2010 BMW E60 continues to embody BMW's commitment to creating vehicles that deliver an exceptional driving experience. With its iconic design, luxurious interior, and engaging performance, the E60 remains a symbol of BMW's dedication to producing vehicles that cater to enthusiasts and luxury-seekers alike.", 2993.0, 9.0, 1, 286.0, "https://i.pinimg.com/originals/51/62/d5/5162d58a4f273c8ce26544da15659b5d.jpg", "BMW", "E60", 18500.0, 190.0, null, null, null, 250.0, 580.0, 1, 1660.0, 2010 },
                    { 243, 5.0999999999999996, 2, "White", 21, "The Toyota Supra, introduced in 1993, is an iconic sports car that embodies Toyota's pursuit of performance, style, and innovation. With its distinctive design, the Supra carries an unmistakable presence on the road. The sleek and aerodynamic body lines reflect both form and function, showcasing a blend of elegance and sportiness. Inside the Supra, the driver-focused cockpit emphasizes a connection between the driver and the road. High-quality materials, supportive seating, and intuitive controls create an environment that caters to both performance and comfort. Under the hood, the Supra offers a robust and turbocharged engine, delivering exhilarating acceleration and a thrilling driving experience. The precise handling and balanced suspension system make it a joy to navigate winding roads and tracks alike. While safety features in the 1993 Supra might not be as advanced as those in modern cars, it offers essential features like airbags and anti-lock brakes to ensure a level of occupant protection. As a part of Toyota's lineup, the Supra remains a symbol of the brand's dedication to engineering excellence and innovation. It's a coveted choice for enthusiasts and drivers seeking a sports car that offers both performance and prestige. In conclusion, the 1993 Toyota Supra stands as a testament to Toyota's commitment to creating a sports car that excites and inspires. With its iconic design, thrilling performance, and driver-focused interior, the Supra continues to hold a special place in the hearts of automotive enthusiasts and remains a timeless representation of Toyota's dedication to delivering excitement on the road.", 2997.0, 14.6, 2, 330.0, "https://media.suara.com/pictures/653x366/2019/05/23/91189-toyota-supra-mk4.jpg", "Toyota", "Supra", 60000.0, 300.0, null, null, null, 250.0, 440.0, 2, 1570.0, 1993 },
                    { 244, 5.7000000000000002, 3, "Black", 14, "The Audi S3 8P, introduced in 2006, is a performance-oriented compact car that represents Audi's dedication to combining power, sophistication, and driving dynamics. With its understated yet sporty design, the S3 8P carries Audi's signature styling cues. The sleek lines and aggressive stance give the car a dynamic presence on the road, while subtle details hint at its performance capabilities. Inside, the S3 8P offers a well-appointed interior that caters to both comfort and sportiness. High-quality materials, supportive seating, and a driver-centric layout create an environment that aligns with Audi's commitment to luxury and performance. Under the hood, the S3 8P is powered by a potent turbocharged engine, delivering exhilarating acceleration and a spirited driving experience. The sport-tuned suspension and responsive steering contribute to the car's engaging handling and precise control. While safety features in the 2006 S3 8P might not be as advanced as those found in newer vehicles, it offers standard airbags, stability control, and other essential systems to ensure occupant protection. As a part of Audi's lineup, the S3 8P showcases the brand's passion for engineering vehicles that offer performance without compromising on luxury. It's a sought-after choice for enthusiasts who seek a compact car that delivers driving excitement. In summary, the 2006 Audi S3 8P stands as a testament to Audi's commitment to producing performance-oriented vehicles. With its sporty design, exhilarating performance, and refined interior, the S3 8P continues to capture the essence of Audi's dedication to creating cars that offer both thrill and sophistication on the road.", 1984.0, 12.4, 2, 265.0, "https://www.ilr-carbon.com/1603-large_default/audi-a3-s3-8p-3-dr-rear-spoiler-rs3-style.jpg", "Audi", "S3 8P", 15400.0, 210.0, null, null, null, 250.0, 350.0, 2, 1455.0, 2006 },
                    { 245, 6.9000000000000004, 6, "Black", 14, "The BMW E64, introduced in 2007, is a convertible that embodies BMW's pursuit of luxury, open-air driving, and performance. With its elegant design, the E64 carries BMW's signature styling cues. The sleek lines and graceful proportions translate seamlessly into the convertible form, creating a harmonious blend of aesthetics and functionality. Inside the E64, the cabin offers a blend of comfort and sophistication. High-quality materials, meticulous craftsmanship, and thoughtful details create an environment that caters to both driver and passenger enjoyment. The convertible configuration adds an extra layer of excitement to the driving experience. Under the hood, the E64 presents a range of engine options, each delivering a balance between performance and refinement. The convertible's chassis and suspension are well-tuned to provide a controlled and engaging ride, whether the top is up or down. While the E64 might not feature the most advanced infotainment systems found in newer BMWs, it provides essential connectivity and entertainment features to enhance the driving experience. As a part of BMW's lineup, the E64 reflects the brand's commitment to producing vehicles that offer a blend of luxury and driving pleasure. It's a desirable choice for drivers seeking a convertible that encapsulates the thrill of open-air motoring. In conclusion, the 2007 BMW E64 remains a testament to BMW's dedication to delivering luxury and performance in a convertible package. With its timeless design, refined interior, and engaging driving dynamics, the E64 continues to capture the essence of BMW's philosophy of creating vehicles that provide a unique and exhilarating driving experience.", 2996.0, 11.800000000000001, 2, 272.0, "https://www.auto-data.net/images/f37/BMW-6-Series-Convertible-E64-facelift-2007.jpg", "BMW", "E64", 24000.0, 260.0, null, null, null, 250.0, 320.0, 2, 1740.0, 2007 },
                    { 246, 7.2000000000000002, 2, "Black", 14, "The BMW E46, introduced in 2003, is a compact luxury car that exemplifies BMW's commitment to performance, driving dynamics, and refined design. With its timeless design, the E46 carries BMW's iconic styling cues. The balanced proportions, clean lines, and distinctive front grille create an appearance that combines elegance with a touch of sportiness. Inside the E46, the cabin offers a blend of comfort and driver-oriented design. High-quality materials, meticulous attention to detail, and intuitive controls contribute to an environment that caters to both driver and passenger satisfaction. The cockpit layout fosters a connection between the driver and the road. Under the hood, the E46 presents a range of engine options, each delivering a balance between power and efficiency. The well-tuned suspension system and responsive steering provide an engaging driving experience that blends comfort and sportiness. While the E46's technology might not be as advanced as that of modern cars, it offers essential amenities to enhance the driving experience, including infotainment and connectivity features. As a part of BMW's lineup, the E46 reflects the brand's commitment to producing vehicles that offer dynamic driving characteristics and a touch of luxury. It's a sought-after choice for enthusiasts and drivers seeking a compact car that provides both performance and prestige. In conclusion, the 2003 BMW E46 stands as a testament to BMW's dedication to engineering vehicles that offer a balance of performance and refinement. With its timeless design, driver-focused interior, and engaging driving dynamics, the E46 continues to capture the essence of BMW's philosophy of delivering the ultimate driving experience.", 2993.0, 9.0999999999999996, 1, 204.0, "https://cloud.leparking.fr/2021/09/07/00/14/bmw-serie-3-coupe-bmw-e46-330cd-coupe-manual-rare-colour-xenons-satnav-heated-seats-bleu_8263957425.jpg", "BMW", "E46", 8100.0, 150.0, null, null, null, 250.0, 410.0, 2, 1540.0, 2003 },
                    { 247, 10.199999999999999, 8, "White", 21, "The Toyota Corolla Verso II, introduced in 2004, is a versatile and practical compact MPV that exemplifies Toyota's commitment to reliability, functionality, and family-friendly design. With its unassuming yet functional design, the Corolla Verso II embodies Toyota's approach to creating vehicles that cater to everyday needs. The compact dimensions, efficient use of space, and practical features contribute to its suitability for family-oriented use. Inside the Corolla Verso II, the cabin offers a flexible and user-friendly layout. Seating configurations can be adjusted to accommodate passengers or cargo, making it adaptable for various situations. The emphasis on functionality extends to the controls and features, which prioritize ease of use. Under the hood, the Corolla Verso II offers a range of efficient engine options, delivering reliable and economical performance for both city and highway driving. The vehicle's suspension system provides a comfortable and stable ride, enhancing passenger comfort. While the Corolla Verso II's technology might not be as advanced as that of newer MPVs, it offers essential features to enhance convenience and entertainment during journeys. As part of Toyota's lineup, the Corolla Verso II reflects the brand's reputation for reliability and practicality. It's a practical choice for families and drivers seeking a compact MPV that offers functionality and dependability. In conclusion, the 2004 Toyota Corolla Verso II stands as a testament to Toyota's dedication to engineering vehicles that address practical needs. With its adaptable design, family-friendly interior, and efficient performance, the Corolla Verso II continues to uphold Toyota's legacy of producing vehicles that cater to a wide range of drivers' requirements.", 2231.0, 8.3000000000000007, 1, 136.0, "https://d1gymyavdvyjgt.cloudfront.net/drive/images/made/drive/images/remote/https_ssl.caranddriving.com/f2/images/used/big/toycorollaverso%202006_750_500_70.jpg", "Toyota", "Corolla Verso II", 6800.0, 70.0, null, null, null, 250.0, 310.0, 2, 1575.0, 2004 },
                    { 248, 6.0, 2, "Grey", 14, "The Mercedes-Benz C-Class, introduced in 2016, represents a harmonious blend of luxury, performance, and advanced technology within the compact luxury sedan segment. With its refined and stylish design, the C-Class carries Mercedes-Benz's signature aesthetic. The sleek body lines and distinctive front grille create an elegant and modern appearance that captures attention on the road. Inside the C-Class, the cabin offers a haven of luxury and sophistication. High-quality materials, meticulous attention to detail, and cutting-edge technology create an interior that caters to both driver and passenger comfort. The intuitive infotainment system and user-friendly controls contribute to an elevated driving experience. Under the hood, the C-Class presents a range of engine options, each delivering a balance between power and efficiency. The sedan's well-tuned suspension system provides a smooth and composed ride, ensuring a refined driving dynamic. In terms of safety and technology, the C-Class is equipped with a comprehensive set of features. Advanced driver assistance systems, including adaptive cruise control, automatic emergency braking, and lane departure warning, enhance driver confidence and occupant protection. As a part of Mercedes-Benz's lineup, the C-Class exemplifies the brand's dedication to engineering excellence and luxury. It's a coveted choice for drivers seeking a compact luxury sedan that offers a blend of elegance, performance, and technological innovation. In conclusion, the 2016 Mercedes-Benz C-Class remains a testament to Mercedes-Benz's commitment to delivering luxury and refinement in a compact package. With its sophisticated design, opulent interior, and advanced safety and technology features, the C-Class continues to capture the essence of Mercedes-Benz's philosophy of creating vehicles that provide an exceptional driving experience.", 1991.0, 8.3000000000000007, 2, 245.0, "https://www.auto-data.net/images/f22/file8603854.jpg", "Mercedes-Benz", "C-Class", 5200.0, 135.0, null, null, null, 250.0, 370.0, 1, 1490.0, 2016 },
                    { 249, 6.7999999999999998, 4, "White", 21, "The Toyota Land Cruiser, introduced in 2003, embodies Toyota's legacy of rugged durability, off-road capability, and timeless design within the realm of SUVs. With its iconic and robust design, the Land Cruiser showcases Toyota's commitment to creating vehicles that can conquer diverse terrains. The bold exterior lines, prominent grille, and sturdy construction emphasize the vehicle's capability both on and off the road. Inside the Land Cruiser, the cabin offers a functional and comfortable environment. Practicality and utility take precedence, with durable materials and a layout designed to withstand demanding conditions. The focus on reliability extends to the controls and features, ensuring a dependable and straightforward driving experience. Under the hood, the Land Cruiser presents a powerful engine and a robust four-wheel-drive system, designed to tackle challenging landscapes with confidence. The vehicle's suspension and chassis provide a comfortable ride while maintaining the ability to handle rough terrain. In terms of technology, the 2003 Land Cruiser might not offer the same level of modern amenities found in contemporary SUVs, but it provides essential features for a comfortable journey. As part of Toyota's lineup, the Land Cruiser remains a symbol of the brand's reputation for dependability and off-road prowess. It's a sought-after choice for adventurers and drivers seeking a reliable SUV that can handle both urban environments and the great outdoors. In conclusion, the 2003 Toyota Land Cruiser stands as a testament to Toyota's commitment to producing rugged and capable SUVs. With its enduring design, functional interior, and impressive off-road capabilities, the Land Cruiser continues to uphold Toyota's legacy of engineering vehicles that are built to withstand the test of time and conquer diverse landscapes.", 3444.0, 18.5, 2, 415.0, "https://www.auto-data.net/images/f109/Toyota-Land-Cruiser-J300.jpg", "Toyota", "Land Cruiser", 85000.0, 190.0, null, null, null, 250.0, 650.0, 1, 2520.0, 2003 },
                    { 250, 8.5999999999999996, 5, "Blue", 14, "The BMW E91, introduced in 2005, is a versatile and stylish wagon that embodies BMW's commitment to combining performance, practicality, and dynamic design. With its sleek yet functional design, the E91 carries BMW's iconic styling cues. The balanced proportions, clean lines, and attention to detail create an appearance that is both elegant and athletic. Inside the E91, the cabin offers a harmonious blend of comfort and utility. High-quality materials, ergonomic design, and ample cargo space make it a practical choice for drivers seeking versatility without sacrificing luxury. The driver-centric layout ensures an engaging and intuitive driving experience. Under the hood, the E91 presents a range of engine options, each delivering a balance between power and efficiency. The vehicle's suspension system and responsive steering contribute to a dynamic and enjoyable driving dynamic, whether navigating city streets or highways. While the E91's technology might not be as advanced as that of newer models, it offers essential features to enhance the driving experience, including connectivity and entertainment options. As a part of BMW's lineup, the E91 reflects the brand's dedication to producing vehicles that offer driving pleasure without compromising on functionality. It's a desirable choice for drivers who seek a wagon that delivers both performance and practicality. In conclusion, the 2005 BMW E91 stands as a testament to BMW's commitment to engineering vehicles that offer a blend of performance and versatility. With its sleek design, functional interior, and engaging driving dynamics, the E91 continues to capture the essence of BMW's philosophy of creating vehicles that provide the best of both worlds – style and practicality.", 1995.0, 8.0999999999999996, 1, 163.0, "https://www.auto-data.net/images/f41/BMW-3-Series-Touring-E91.jpg", "BMW", "E91", 8200.0, 140.0, null, null, null, 223.0, 340.0, 2, 1510.0, 2005 },
                    { 251, 6.7999999999999998, 7, "Yellow", 14, "The Dodge Ram, introduced in 2005, is a rugged and capable full-size pickup truck that embodies Dodge's commitment to power, utility, and distinctive design. With its bold and muscular design, the Ram carries Dodge's signature styling cues. The robust grille, chiseled lines, and imposing stance create an appearance that exudes strength and capability. Inside the Ram, the cabin offers a functional and spacious environment. Utilitarian materials, comfortable seating, and a layout designed for practicality make it well-suited for both work and everyday driving. The emphasis on functionality extends to the controls and features, prioritizing ease of use. Under the hood, the Ram presents a range of powerful engine options, delivering impressive towing and hauling capabilities. The truck's sturdy chassis and suspension system contribute to a stable and confident ride, whether carrying heavy loads or navigating rough terrains. While the 2005 Ram's technology might not match the advanced features of modern trucks, it provides essential amenities to enhance both work and leisure, including entertainment and connectivity options. As part of Dodge's lineup, the Ram reflects the brand's reputation for producing vehicles that cater to drivers who demand performance and versatility. It's a sought-after choice for truck enthusiasts and drivers seeking a dependable and robust pickup truck. In conclusion, the 2005 Dodge Ram stands as a testament to Dodge's commitment to engineering trucks that offer power and utility. With its commanding design, practical interior, and robust capabilities, the Ram continues to uphold Dodge's legacy of creating vehicles that can tackle tough tasks and deliver a dependable performance in various scenarios.", 5657.0, 18.100000000000001, 2, 345.0, "https://www.auto-data.net/images/f46/Dodge-Ram-1500-III-DR-DH.jpg", "Dodge", "Ram", 3700.0, 330.0, null, null, null, 250.0, 529.0, 1, 1880.0, 2005 },
                    { 252, 11.1, 4, "Red", 21, "The Dacia Sandero II Stepway, introduced in 2013, is a practical and affordable compact crossover that embodies Dacia's commitment to simplicity, value, and functionality. With its rugged and utilitarian design, the Sandero II Stepway carries Dacia's straightforward styling cues. The elevated ground clearance, protective cladding, and distinctive front grille create an appearance that balances practicality and adventure. Inside the Sandero II Stepway, the cabin offers a straightforward and functional layout. Basic yet durable materials, ergonomic seating, and practical storage solutions make it well-suited for drivers seeking a no-frills approach to driving. Under the hood, the Sandero II Stepway presents efficient engine options, delivering dependable performance for everyday commuting and urban driving. The crossover's slightly raised suspension system provides enhanced ground clearance and a comfortable ride, suitable for varied road conditions. While the 2013 Sandero II Stepway's technology might not be as advanced as that of modern crossovers, it offers essential features to enhance the driving experience, focusing on practicality rather than luxury. As part of Dacia's lineup, the Sandero II Stepway reflects the brand's reputation for producing vehicles that prioritize value and functionality. It's a practical choice for drivers seeking a budget-friendly crossover that meets basic transportation needs. In conclusion, the 2013 Dacia Sandero II Stepway stands as a testament to Dacia's philosophy of providing affordable and straightforward vehicles. With its rugged design, functional interior, and dependable performance, the Sandero II Stepway continues to uphold Dacia's legacy of creating vehicles that offer practicality and value for budget-conscious drivers.", 2999.0, 6.7000000000000002, 2, 90.0, "https://cdn3.focus.bg/autodata/i/dacia/sandero/sandero-ii-stepway/large/675829b961ab0a61241270896e202b87.jpg", "Dacia", "Sandero II Stepway", 9999.0, 199.0, null, null, null, 170.0, 135.0, 2, 1023.0, 2013 },
                    { 253, 10.800000000000001, 3, "Black", 14, "The Mercedes-Benz A-Class (W168), introduced in 1999, is a compact car that embodies Mercedes-Benz's commitment to innovation, versatility, and safety. With its distinctive design, the A-Class (W168) showcases Mercedes-Benz's approach to creating compact vehicles that offer practicality without sacrificing style. The unique tall body design and compact dimensions create an appearance that maximizes interior space while remaining compact and agile. Inside the A-Class (W168), the cabin offers a surprisingly roomy and flexible environment. Smart space utilization, ergonomic seating, and practical storage solutions make it suitable for both urban driving and longer journeys. The driver-centric layout reflects Mercedes-Benz's dedication to creating user-friendly interiors. Under the hood, the A-Class (W168) presents a range of engine options, delivering efficient performance for various driving scenarios. The vehicle's suspension system provides a balanced and comfortable ride, suitable for navigating city streets and highways. While the 1999 A-Class (W168) might not feature the same level of technology as more recent Mercedes-Benz models, it offers essential amenities to enhance the driving experience, focusing on comfort and convenience. As part of Mercedes-Benz's lineup, the A-Class (W168) reflects the brand's commitment to engineering vehicles that cater to diverse driver needs. It's a practical choice for drivers seeking a compact car that offers Mercedes-Benz's reputation for quality and safety. In conclusion, the 1999 Mercedes-Benz A-Class (W168) stands as a testament to Mercedes-Benz's philosophy of creating vehicles that combine innovation and functionality. With its distinctive design, versatile interior, and emphasis on safety, the A-Class (W168) continues to capture the essence of Mercedes-Benz's dedication to producing vehicles that adapt to the evolving needs of drivers.", 1598.0, 10.199999999999999, 2, 102.0, "https://static-eu.cargurus.com/images/forsale/2023/05/16/15/02/2003_mercedes-benz_a-class-pic-3974413017599453644-1024x768.jpeg", "Mercedes-Benz", "A-Class (W168)", 4400.0, 110.0, null, null, null, 180.0, 150.0, 2, 1135.0, 1999 },
                    { 254, 8.0999999999999996, 1, "Grey", 14, "The Audi A4, introduced in 2011, represents Audi's commitment to luxury, performance, and innovative design. With a sleek and modern exterior, the A4 boasts Audi's signature aesthetic, characterized by clean lines, a distinctive grille, and balanced proportions. Inside the cabin, high-quality materials, meticulous craftsmanship, and advanced technology come together to create a refined and comfortable environment. The A4 offers a range of engine options that balance power and efficiency, while its suspension and steering provide a dynamic driving experience. Equipped with advanced safety and technology features like adaptive cruise control, automatic emergency braking, and lane departure warning, the 2011 A4 prioritizes driver confidence and occupant protection. As a part of Audi's lineup, the A4 embodies the brand's commitment to luxury and engineering excellence. It remains a sought-after choice for those seeking a compact luxury sedan that marries style, performance, and technological innovation seamlessly.", 1798.0, 7.4000000000000004, 2, 170.0, "https://www.auto-data.net/images/f93/Audi-A4-B8-8K-facelift-2011.jpg", "Audi", "A4", 12400.0, 180.0, null, null, null, 230.0, 320.0, 2, 1430.0, 2011 },
                    { 255, 3.6000000000000001, 1, "Black", 14, "The Porsche Panamera G2, introduced in 2019, is a luxury sports sedan that showcases Porsche's dedication to performance, innovation, and refined design. With its sleek and athletic design, the Panamera G2 embodies Porsche's iconic styling cues. The sweeping lines, distinctive headlights, and wide stance create an appearance that seamlessly combines elegance with sportiness. Inside the Panamera G2, the cabin offers a luxurious and driver-focused environment. High-quality materials, meticulous attention to detail, and cutting-edge technology create an interior that caters to both driver and passenger satisfaction. The intuitive infotainment system and driver assistance features enhance the driving experience. Under the hood, the Panamera G2 presents a range of powerful engine options, delivering exhilarating acceleration and impressive handling characteristics. The sedan's advanced suspension system and responsive steering contribute to a dynamic and engaging driving experience. In terms of safety and technology, the 2019 Panamera G2 is equipped with a suite of advanced features, including adaptive cruise control, lane keeping assist, and automatic emergency braking. These systems work together to enhance driver confidence and occupant protection. As part of Porsche's lineup, the Panamera G2 reflects the brand's commitment to engineering excellence and driving pleasure. It's a coveted choice for drivers seeking a luxury sports sedan that offers a blend of style, performance, and cutting-edge technology. In conclusion, the 2019 Porsche Panamera G2 stands as a testament to Porsche's philosophy of creating vehicles that deliver both luxury and performance. With its striking design, opulent interior, and advanced safety and technology features, the Panamera G2 continues to capture the essence of Porsche's dedication to providing an exceptional driving experience.", 3996.0, 14.4, 2, 550.0, "https://www.auto-data.net/images/f15/file8561600.jpg", "Porsche", "Panamera G2", 175000.0, 100.0, null, null, null, 306.0, 770.0, 1, 1995.0, 2019 },
                    { 256, 4.4000000000000004, 2, "Black", 21, "The BMW E92 M3 is a high-performance sports coupe known for its powerful V8 engine, precise handling, and iconic design. With a perfect blend of luxury and exhilaration, it remains a favorite among car enthusiasts seeking a thrilling driving experience.", 4361.0, 18.5, 2, 450.0, "https://pbs.twimg.com/media/Ei3lNlHXsAAoMQD.jpg", "BMW", "E92 M3", 66500.0, 600.0, null, null, null, 250.0, 440.0, 1, 1530.0, 2010 },
                    { 257, 3.6000000000000001, 2, "Black", 21, "The Mercedes CLS 63 AMG is a luxury four-door coupe that combines elegance with blistering performance. Powered by a potent V8 engine, it offers a comfortable yet exhilarating driving experience, setting new standards for high-end performance cars.", 5461.0, 14.4, 2, 585.0, "https://citycarrentals.ca/wp-content/uploads/2018/02/mercedes-benz-cls-63-amg-black-3.jpg", "Mercedes-Benz", "CLS 63 AMG", 67500.0, 680.0, null, null, null, 250.0, 800.0, 1, 1945.0, 2014 },
                    { 258, 5.0999999999999996, 2, "Black", 21, "The Audi S5 is a dynamic and sleek sports coupe, featuring a turbocharged V6 engine and Quattro all-wheel drive. Its blend of performance, comfort, and cutting-edge technology make it a compelling choice for driving enthusiasts with a taste for luxury.", 2999.0, 10.699999999999999, 2, 333.0, "https://i.pinimg.com/originals/4f/23/28/4f2328613a9577fef6f77eee198e5f65.jpg", "Audi", "S5", 64000.0, 510.0, null, null, null, 250.0, 440.0, 1, 1745.0, 2012 },
                    { 259, 1.1000000000000001, 1, "Black", 21, "TestDesc1", 444.0, 11.0, 1, 333.0, "https://images.drive.com.au/driveau/image/upload/t_wp-default/v1/cms/uploads/jjslyagf8e3gcny2doyy", "TestMake1", "TestModel1", 1234.0, 111.0, null, null, null, 123.0, 333.0, 1, 1234.0, 2011 }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 236);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 237);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 238);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 239);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 240);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 241);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 242);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 243);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 244);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 245);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 246);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 247);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 248);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 249);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 250);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 251);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 252);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 253);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 254);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 255);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 256);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 257);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 258);

            migrationBuilder.DeleteData(
                table: "Cars",
                keyColumn: "CarId",
                keyValue: 259);

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "asd4f072-ecca-43c9-ab26-c060c6f364e4",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "d93434eb-2485-4142-806d-f43e009baeed", "AQAAAAEAACcQAAAAEAeTg23M2BmTslN2DSK+5EGbJl8hdWUD5kTwUaMSf+avQtz0gfO+dmvlqMIM9if0eQ==", "6989fc5a-67e4-40e8-84e4-f2871b60fba7" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "bcb4f072-ecca-43c9-ab26-c060c6f364e4",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "a21db937-0edc-4ec9-a208-2bdea32992d1", "AQAAAAEAACcQAAAAEDGo2pFvzNNeU8fSODyPoUZ5skVWq4RLttrFwHA8t3seZZV6oDEw9mZZjQ666TAlMQ==", "31d4bf52-2dc9-4e3a-a6ba-6afbc54fb185" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "qwe4f072-ecca-43c9-ab26-c060c6f364e4",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "2501faa5-6d79-495a-88de-a9f952995d47", "AQAAAAEAACcQAAAAEK8CPqNp7W8mapKOBadURcxsS2kZpb7pDEzziZDNm46d5K7mOQOIdwo/d5wVTzTrqw==", "51568dd4-f41a-4e3f-ba06-fda5170bad0e" });

            migrationBuilder.InsertData(
                table: "Cars",
                columns: new[] { "CarId", "Acceleration", "CategoryId", "Color", "DealerId", "Description", "EngineSize", "FuelConsumption", "FuelTypeId", "Horsepower", "ImageUrl", "Make", "Model", "Price", "RentPrice", "RentalEndDate", "RentalStartDate", "RenterId", "TopSpeed", "Torque", "TransmissionId", "Weight", "Year" },
                values: new object[,]
                {
                    { 207, 4.9000000000000004, 1, "Black", 14, "The Mercedes-Benz S-Class (W223), a pinnacle of luxury and engineering excellence, continues its legacy in the year 2022. Renowned for its opulent features, cutting-edge technology, and refined performance, the S-Class remains a symbol of sophistication and prestige. The exterior design of the S-Class (W223) strikes a balance between timeless elegance and modern aesthetics. The body lines exude a sense of fluidity and strength, while the meticulously crafted details showcase the brand's commitment to perfection. Inside, the cabin offers an oasis of comfort and luxury. Premium materials, exquisite craftsmanship, and advanced features create an ambiance that indulges the senses. Mercedes-Benz's latest innovations are seamlessly integrated into the S-Class. The state-of-the-art MBUX infotainment system greets occupants with intuitive controls, voice commands, and a futuristic digital cockpit. Augmented reality navigation, AI-powered predictive functions, and customizable displays elevate the driving experience. Under the hood, the S-Class offers an array of potent powertrains, catering to diverse preferences. From refined gasoline and diesel engines to electrified options, each variant delivers a harmonious blend of power and efficiency. The advanced suspension system ensures a smooth and controlled ride, even on challenging road surfaces. Mercedes-Benz's commitment to safety is exemplified by the S-Class (W223). The vehicle incorporates an array of advanced driver assistance systems, including adaptive cruise control, lane-keeping assist, automatic emergency braking, and more. These features work together to enhance driver confidence and mitigate potential risks. The S-Class is renowned for introducing groundbreaking innovations, and the W223 is no exception. It boasts technologies such as E-Active Body Control, which uses cameras to scan the road and adjust the suspension accordingly, providing unparalleled comfort and stability. In conclusion, the Mercedes-Benz S-Class (W223) exemplifies the brand's dedication to luxury, technology, and performance. As a flagship model, it continues to set the standard for the automotive industry, redefining what it means to travel in style and comfort. With its timeless design and cutting-edge features, the S-Class remains an icon of automotive excellence in the year 2022.", 2999.0, 0.69999999999999996, 4, 365.0, "https://www.auto-data.net/images/f94/Mercedes-Benz-S-class-W223.jpg", "Mercedes-Benz", "S-Class (W223)", 175000.0, 700.0, null, null, null, 250.0, 500.0, 1, 2345.0, 2022 },
                    { 208, 12.9, 3, "black", 14, "The VW Golf 5, launched in 2004, is a part of Volkswagen's renowned Golf lineup. It blends practicality, reliability, and driving enjoyment seamlessly. With a design that balances aesthetics and modern simplicity, the Golf 5's compact dimensions offer style without sacrificing functionality. Inside, the cabin emphasizes user-friendly controls, comfortable seating, and ample cargo space. Under the hood, the Golf 5 presents a range of engine options, each delivering a mix of efficiency and performance. Responsive steering and a well-tuned suspension contribute to a confident driving experience. While not equipped with the latest technology, the Golf 5's interior provides essential comforts, reflecting Volkswagen's commitment to quality. In terms of safety, the Golf 5 incorporates airbags, anti-lock brakes, and stability control for occupant protection. As a significant iteration in the Golf lineup, the Golf 5 upholds the model's reputation for reliability and practicality, appealing to drivers seeking an affordable and dependable option. In summary, the 2004 VW Golf 5 remains a symbol of reliability and practicality within the compact car segment. Its enduring design, balanced performance, and comfort continue to exemplify Volkswagen's dedication to meeting diverse driver needs.", 1896.0, 6.5, 1, 90.0, "https://www.auto-data.net/images/f118/Volkswagen-Golf-V.jpg", "VW", "Golf 5", 6200.0, 40.0, null, null, null, 176.0, 210.0, 1, 1285.0, 2004 },
                    { 209, 10.1, 3, "Red", 21, "The Skoda Fabia III, introduced in 2018 by Skoda, embodies practicality, efficiency, and modern design in the compact car segment. With its sleek exterior and contemporary lines, the Fabia III boasts a design that merges aesthetics with functionality. The compact dimensions make it maneuverable in urban environments while offering ample interior space for passengers and cargo. Under the hood, the Fabia III offers a range of efficient engines, catering to both city commuting and longer journeys. Its balanced performance strikes a chord between fuel efficiency and driving enjoyment. The cabin of the Fabia III reflects Skoda's commitment to user-centered design. The interior space is intelligently organized, providing ergonomic seating and intuitive controls. Modern connectivity features ensure a convenient driving experience. In terms of safety, the Fabia III is equipped with standard airbags, anti-lock brakes, stability control, and more. While not the most advanced in terms of safety tech, it delivers a reassuring level of protection. As a part of Skoda's lineup, the Fabia III aligns with the brand's reputation for reliability and practicality. It's an ideal choice for drivers seeking a compact car that effortlessly combines style and functionality. In conclusion, the 2018 Skoda Fabia III stands as a testament to Skoda's commitment to producing compact cars that excel in practicality and efficiency. With its modern design, well-organized interior, and balanced performance, the Fabia III remains a relevant choice for drivers looking for a reliable and stylish urban companion.", 2993.0, 5.5999999999999996, 2, 110.0, "https://www.auto-data.net/images/f76/Skoda-Fabia-III-facelift-2018.jpg", "Skoda", "Fabia III", 24000.0, 130.0, null, null, null, 195.0, 200.0, 2, 1957.0, 2018 },
                    { 210, 6.7999999999999998, 4, "Dark blue", 14, "The Lexus RX IV, introduced in 2016 by Lexus, is a luxury SUV that blends sophistication, advanced technology, and comfort in a seamless package. Characterized by its bold and distinctive design, the RX IV commands attention on the road. The sharp lines and signature Lexus spindle grille contribute to its upscale presence, while the attention to detail showcases the brand's commitment to craftsmanship. Inside the RX IV, the cabin offers a sanctuary of luxury and modernity. High-quality materials, exquisite finishes, and meticulously crafted details create an ambiance that indulges the senses. The intuitive layout and user-friendly controls contribute to an effortless driving experience. Under the hood, the RX IV offers a range of powerful and efficient engine options, delivering both performance and fuel economy. The advanced suspension system ensures a smooth and composed ride, making it well-suited for both city driving and long journeys. Lexus is synonymous with cutting-edge technology, and the RX IV is no exception. It incorporates a suite of advanced features, including a user-friendly infotainment system, driver assistance technologies, and a premium sound system, elevating the driving experience to new heights. In terms of safety, the RX IV is equipped with a comprehensive set of features, including adaptive cruise control, lane departure warning, automatic emergency braking, and more. These systems work in harmony to enhance driver confidence and mitigate potential risks. As a flagship SUV in Lexus's lineup, the RX IV exemplifies the brand's dedication to luxury and innovation. Its combination of bold design, refined interior, and advanced technology positions it as a compelling choice in the luxury SUV segment. In conclusion, the 2016 Lexus RX IV is a testament to Lexus's pursuit of excellence in luxury and performance. With its distinctive design, opulent interior, and state-of-the-art technology, the RX IV continues to capture the essence of modern luxury and remains a symbol of Lexus's commitment to elevating the driving experience.", 3456.0, 11.699999999999999, 2, 290.0, "https://www.auto-data.net/images/f28/file9510003.jpg", "Lexus", "RX IV", 85000.0, 220.0, null, null, null, 200.0, 363.0, 1, 2025.0, 2016 },
                    { 211, 9.5, 1, "White", 14, "The Volvo S40 II, introduced in 2011 by Volvo, represents a harmonious blend of Scandinavian design, safety innovation, and driving dynamics in a compact sedan package. The S40 II's exterior design exudes a distinctive blend of elegance and modernity. Clean lines and a sleek profile capture Volvo's commitment to minimalist aesthetics while conveying a sense of purposeful movement. Inside, the cabin of the S40 II offers a comfortable and intuitive environment. High-quality materials and meticulous attention to detail create an atmosphere that prioritizes both driver and passenger comfort. The user-friendly controls and ergonomic layout contribute to an enjoyable driving experience. Under the hood, the S40 II presents a range of efficient and capable engine options, delivering a balance between performance and fuel economy. The sedan's well-tuned suspension system provides a composed and engaging ride, whether navigating city streets or cruising on the highway. Volvo's reputation for safety innovation shines in the S40 II. The sedan is equipped with a comprehensive set of safety features, including advanced airbag systems, stability control, and Volvo's City Safety system, which can help prevent or mitigate collisions at low speeds. While the S40 II might not offer the most cutting-edge infotainment features, it does provide essential connectivity and entertainment options to enhance the driving experience. As part of Volvo's lineup, the S40 II embodies the brand's commitment to safety and quality. It's a compelling choice for drivers seeking a compact sedan that combines style, comfort, and advanced safety features. In summary, the 2011 Volvo S40 II remains a testament to Volvo's legacy of designing vehicles that prioritize safety, comfort, and Scandinavian aesthetics. With its elegant design, well-appointed interior, and comprehensive safety features, the S40 II continues to reflect Volvo's dedication to engineering vehicles that enhance both the driving experience and occupant well-being.", 1999.0, 10.800000000000001, 2, 145.0, "https://www.auto-data.net/images/f88/Volvo-S40-II-facelift-2007.jpg", "Volvo", "S40 II", 4800.0, 75.0, null, null, null, 200.0, 185.0, 2, 1370.0, 2011 },
                    { 212, 10.699999999999999, 5, "Red", 21, "The Kia Optima IV, introduced in 2018, is a midsize sedan that showcases Kia's commitment to style, technology, and value. With its modern exterior design, the Optima IV captures attention on the road. Sleek lines and a bold front grille create an assertive presence, while the attention to aerodynamics contributes to its efficiency. Inside the Optima IV, the cabin offers a blend of comfort and technology. High-quality materials and well-crafted surfaces create an inviting atmosphere. The intuitive infotainment system provides connectivity and entertainment features that enhance the driving experience. Under the hood, the Optima IV offers a range of engine options, catering to different preferences for performance and fuel efficiency. The sedan's well-balanced suspension and responsive steering contribute to a confident and enjoyable driving dynamic. In terms of safety, the Optima IV is equipped with a suite of features, including adaptive cruise control, automatic emergency braking, lane departure warning, and more. These features work together to enhance driver confidence and mitigate potential risks. As a part of Kia's lineup, the Optima IV represents the brand's commitment to delivering value without compromising on style and technology. It's a practical choice for drivers seeking a midsize sedan that offers a combination of comfort, performance, and safety. In conclusion, the 2018 Kia Optima IV reflects Kia's dedication to providing a well-rounded midsize sedan. With its modern design, comfortable interior, and advanced safety and technology features, the Optima IV remains a relevant choice for drivers who prioritize style and practicality in their daily commute.", 2993.0, 10.1, 2, 163.0, "https://www.auto-data.net/images/f56/Kia-Optima-IV-Sportswagon-facelift-2018.jpg", "Kia", "Optima IV", 3900.0, 360.0, null, null, null, 205.0, 196.0, 1, 1625.0, 2018 },
                    { 213, 6.4000000000000004, 1, "Black", 14, "The BMW E60, introduced in 2010, is a representation of BMW's commitment to luxury, performance, and driving pleasure in the midsize sedan category. With its iconic design, the E60 carries BMW's distinctive styling cues. The elegant yet dynamic lines of the exterior showcase a timeless aesthetic that blends sophistication with athleticism. Inside, the cabin of the E60 offers a driver-focused environment. High-quality materials, precision craftsmanship, and ergonomic design create a space that exudes luxury and comfort. The intuitive controls and advanced infotainment system contribute to an engaging driving experience. Under the hood, the E60 offers a range of powerful engine options, each delivering the performance and refinement expected from a BMW. The sedan's responsive handling and well-tuned suspension system provide a dynamic driving experience that balances comfort and sportiness. Safety features in the E60 include airbags, stability control, and advanced braking systems, which contribute to occupant protection and peace of mind while on the road. As part of BMW's lineup, the E60 upholds the brand's legacy of engineering excellence and driving dynamics. It's an appealing choice for drivers who seek a midsize sedan that offers a blend of luxury, performance, and prestige. In summary, the 2010 BMW E60 continues to embody BMW's commitment to creating vehicles that deliver an exceptional driving experience. With its iconic design, luxurious interior, and engaging performance, the E60 remains a symbol of BMW's dedication to producing vehicles that cater to enthusiasts and luxury-seekers alike.", 2993.0, 9.0, 1, 286.0, "https://i.pinimg.com/originals/51/62/d5/5162d58a4f273c8ce26544da15659b5d.jpg", "BMW", "E60", 18500.0, 190.0, null, null, null, 250.0, 580.0, 1, 1660.0, 2010 },
                    { 214, 5.0999999999999996, 2, "White", 21, "The Toyota Supra, introduced in 1993, is an iconic sports car that embodies Toyota's pursuit of performance, style, and innovation. With its distinctive design, the Supra carries an unmistakable presence on the road. The sleek and aerodynamic body lines reflect both form and function, showcasing a blend of elegance and sportiness. Inside the Supra, the driver-focused cockpit emphasizes a connection between the driver and the road. High-quality materials, supportive seating, and intuitive controls create an environment that caters to both performance and comfort. Under the hood, the Supra offers a robust and turbocharged engine, delivering exhilarating acceleration and a thrilling driving experience. The precise handling and balanced suspension system make it a joy to navigate winding roads and tracks alike. While safety features in the 1993 Supra might not be as advanced as those in modern cars, it offers essential features like airbags and anti-lock brakes to ensure a level of occupant protection. As a part of Toyota's lineup, the Supra remains a symbol of the brand's dedication to engineering excellence and innovation. It's a coveted choice for enthusiasts and drivers seeking a sports car that offers both performance and prestige. In conclusion, the 1993 Toyota Supra stands as a testament to Toyota's commitment to creating a sports car that excites and inspires. With its iconic design, thrilling performance, and driver-focused interior, the Supra continues to hold a special place in the hearts of automotive enthusiasts and remains a timeless representation of Toyota's dedication to delivering excitement on the road.", 2997.0, 14.6, 2, 330.0, "https://media.suara.com/pictures/653x366/2019/05/23/91189-toyota-supra-mk4.jpg", "Toyota", "Supra", 60000.0, 300.0, null, null, null, 250.0, 440.0, 2, 1570.0, 1993 },
                    { 215, 5.7000000000000002, 3, "Black", 14, "The Audi S3 8P, introduced in 2006, is a performance-oriented compact car that represents Audi's dedication to combining power, sophistication, and driving dynamics. With its understated yet sporty design, the S3 8P carries Audi's signature styling cues. The sleek lines and aggressive stance give the car a dynamic presence on the road, while subtle details hint at its performance capabilities. Inside, the S3 8P offers a well-appointed interior that caters to both comfort and sportiness. High-quality materials, supportive seating, and a driver-centric layout create an environment that aligns with Audi's commitment to luxury and performance. Under the hood, the S3 8P is powered by a potent turbocharged engine, delivering exhilarating acceleration and a spirited driving experience. The sport-tuned suspension and responsive steering contribute to the car's engaging handling and precise control. While safety features in the 2006 S3 8P might not be as advanced as those found in newer vehicles, it offers standard airbags, stability control, and other essential systems to ensure occupant protection. As a part of Audi's lineup, the S3 8P showcases the brand's passion for engineering vehicles that offer performance without compromising on luxury. It's a sought-after choice for enthusiasts who seek a compact car that delivers driving excitement. In summary, the 2006 Audi S3 8P stands as a testament to Audi's commitment to producing performance-oriented vehicles. With its sporty design, exhilarating performance, and refined interior, the S3 8P continues to capture the essence of Audi's dedication to creating cars that offer both thrill and sophistication on the road.", 1984.0, 12.4, 2, 265.0, "https://www.ilr-carbon.com/1603-large_default/audi-a3-s3-8p-3-dr-rear-spoiler-rs3-style.jpg", "Audi", "S3 8P", 15400.0, 210.0, null, null, null, 250.0, 350.0, 2, 1455.0, 2006 },
                    { 216, 6.9000000000000004, 6, "Black", 14, "The BMW E64, introduced in 2007, is a convertible that embodies BMW's pursuit of luxury, open-air driving, and performance. With its elegant design, the E64 carries BMW's signature styling cues. The sleek lines and graceful proportions translate seamlessly into the convertible form, creating a harmonious blend of aesthetics and functionality. Inside the E64, the cabin offers a blend of comfort and sophistication. High-quality materials, meticulous craftsmanship, and thoughtful details create an environment that caters to both driver and passenger enjoyment. The convertible configuration adds an extra layer of excitement to the driving experience. Under the hood, the E64 presents a range of engine options, each delivering a balance between performance and refinement. The convertible's chassis and suspension are well-tuned to provide a controlled and engaging ride, whether the top is up or down. While the E64 might not feature the most advanced infotainment systems found in newer BMWs, it provides essential connectivity and entertainment features to enhance the driving experience. As a part of BMW's lineup, the E64 reflects the brand's commitment to producing vehicles that offer a blend of luxury and driving pleasure. It's a desirable choice for drivers seeking a convertible that encapsulates the thrill of open-air motoring. In conclusion, the 2007 BMW E64 remains a testament to BMW's dedication to delivering luxury and performance in a convertible package. With its timeless design, refined interior, and engaging driving dynamics, the E64 continues to capture the essence of BMW's philosophy of creating vehicles that provide a unique and exhilarating driving experience.", 2996.0, 11.800000000000001, 2, 272.0, "https://www.auto-data.net/images/f37/BMW-6-Series-Convertible-E64-facelift-2007.jpg", "BMW", "E64", 24000.0, 260.0, null, null, null, 250.0, 320.0, 2, 1740.0, 2007 },
                    { 217, 7.2000000000000002, 2, "Black", 14, "The BMW E46, introduced in 2003, is a compact luxury car that exemplifies BMW's commitment to performance, driving dynamics, and refined design. With its timeless design, the E46 carries BMW's iconic styling cues. The balanced proportions, clean lines, and distinctive front grille create an appearance that combines elegance with a touch of sportiness. Inside the E46, the cabin offers a blend of comfort and driver-oriented design. High-quality materials, meticulous attention to detail, and intuitive controls contribute to an environment that caters to both driver and passenger satisfaction. The cockpit layout fosters a connection between the driver and the road. Under the hood, the E46 presents a range of engine options, each delivering a balance between power and efficiency. The well-tuned suspension system and responsive steering provide an engaging driving experience that blends comfort and sportiness. While the E46's technology might not be as advanced as that of modern cars, it offers essential amenities to enhance the driving experience, including infotainment and connectivity features. As a part of BMW's lineup, the E46 reflects the brand's commitment to producing vehicles that offer dynamic driving characteristics and a touch of luxury. It's a sought-after choice for enthusiasts and drivers seeking a compact car that provides both performance and prestige. In conclusion, the 2003 BMW E46 stands as a testament to BMW's dedication to engineering vehicles that offer a balance of performance and refinement. With its timeless design, driver-focused interior, and engaging driving dynamics, the E46 continues to capture the essence of BMW's philosophy of delivering the ultimate driving experience.", 2993.0, 9.0999999999999996, 1, 204.0, "https://cloud.leparking.fr/2021/09/07/00/14/bmw-serie-3-coupe-bmw-e46-330cd-coupe-manual-rare-colour-xenons-satnav-heated-seats-bleu_8263957425.jpg", "BMW", "E46", 8100.0, 150.0, null, null, null, 250.0, 410.0, 2, 1540.0, 2003 },
                    { 218, 10.199999999999999, 8, "White", 21, "The Toyota Corolla Verso II, introduced in 2004, is a versatile and practical compact MPV that exemplifies Toyota's commitment to reliability, functionality, and family-friendly design. With its unassuming yet functional design, the Corolla Verso II embodies Toyota's approach to creating vehicles that cater to everyday needs. The compact dimensions, efficient use of space, and practical features contribute to its suitability for family-oriented use. Inside the Corolla Verso II, the cabin offers a flexible and user-friendly layout. Seating configurations can be adjusted to accommodate passengers or cargo, making it adaptable for various situations. The emphasis on functionality extends to the controls and features, which prioritize ease of use. Under the hood, the Corolla Verso II offers a range of efficient engine options, delivering reliable and economical performance for both city and highway driving. The vehicle's suspension system provides a comfortable and stable ride, enhancing passenger comfort. While the Corolla Verso II's technology might not be as advanced as that of newer MPVs, it offers essential features to enhance convenience and entertainment during journeys. As part of Toyota's lineup, the Corolla Verso II reflects the brand's reputation for reliability and practicality. It's a practical choice for families and drivers seeking a compact MPV that offers functionality and dependability. In conclusion, the 2004 Toyota Corolla Verso II stands as a testament to Toyota's dedication to engineering vehicles that address practical needs. With its adaptable design, family-friendly interior, and efficient performance, the Corolla Verso II continues to uphold Toyota's legacy of producing vehicles that cater to a wide range of drivers' requirements.", 2231.0, 8.3000000000000007, 1, 136.0, "https://d1gymyavdvyjgt.cloudfront.net/drive/images/made/drive/images/remote/https_ssl.caranddriving.com/f2/images/used/big/toycorollaverso%202006_750_500_70.jpg", "Toyota", "Corolla Verso II", 6800.0, 70.0, null, null, null, 250.0, 310.0, 2, 1575.0, 2004 },
                    { 219, 6.0, 2, "Grey", 14, "The Mercedes-Benz C-Class, introduced in 2016, represents a harmonious blend of luxury, performance, and advanced technology within the compact luxury sedan segment. With its refined and stylish design, the C-Class carries Mercedes-Benz's signature aesthetic. The sleek body lines and distinctive front grille create an elegant and modern appearance that captures attention on the road. Inside the C-Class, the cabin offers a haven of luxury and sophistication. High-quality materials, meticulous attention to detail, and cutting-edge technology create an interior that caters to both driver and passenger comfort. The intuitive infotainment system and user-friendly controls contribute to an elevated driving experience. Under the hood, the C-Class presents a range of engine options, each delivering a balance between power and efficiency. The sedan's well-tuned suspension system provides a smooth and composed ride, ensuring a refined driving dynamic. In terms of safety and technology, the C-Class is equipped with a comprehensive set of features. Advanced driver assistance systems, including adaptive cruise control, automatic emergency braking, and lane departure warning, enhance driver confidence and occupant protection. As a part of Mercedes-Benz's lineup, the C-Class exemplifies the brand's dedication to engineering excellence and luxury. It's a coveted choice for drivers seeking a compact luxury sedan that offers a blend of elegance, performance, and technological innovation. In conclusion, the 2016 Mercedes-Benz C-Class remains a testament to Mercedes-Benz's commitment to delivering luxury and refinement in a compact package. With its sophisticated design, opulent interior, and advanced safety and technology features, the C-Class continues to capture the essence of Mercedes-Benz's philosophy of creating vehicles that provide an exceptional driving experience.", 1991.0, 8.3000000000000007, 2, 245.0, "https://www.auto-data.net/images/f22/file8603854.jpg", "Mercedes-Benz", "C-Class", 5200.0, 135.0, null, null, null, 250.0, 370.0, 1, 1490.0, 2016 },
                    { 220, 6.7999999999999998, 4, "White", 21, "The Toyota Land Cruiser, introduced in 2003, embodies Toyota's legacy of rugged durability, off-road capability, and timeless design within the realm of SUVs. With its iconic and robust design, the Land Cruiser showcases Toyota's commitment to creating vehicles that can conquer diverse terrains. The bold exterior lines, prominent grille, and sturdy construction emphasize the vehicle's capability both on and off the road. Inside the Land Cruiser, the cabin offers a functional and comfortable environment. Practicality and utility take precedence, with durable materials and a layout designed to withstand demanding conditions. The focus on reliability extends to the controls and features, ensuring a dependable and straightforward driving experience. Under the hood, the Land Cruiser presents a powerful engine and a robust four-wheel-drive system, designed to tackle challenging landscapes with confidence. The vehicle's suspension and chassis provide a comfortable ride while maintaining the ability to handle rough terrain. In terms of technology, the 2003 Land Cruiser might not offer the same level of modern amenities found in contemporary SUVs, but it provides essential features for a comfortable journey. As part of Toyota's lineup, the Land Cruiser remains a symbol of the brand's reputation for dependability and off-road prowess. It's a sought-after choice for adventurers and drivers seeking a reliable SUV that can handle both urban environments and the great outdoors. In conclusion, the 2003 Toyota Land Cruiser stands as a testament to Toyota's commitment to producing rugged and capable SUVs. With its enduring design, functional interior, and impressive off-road capabilities, the Land Cruiser continues to uphold Toyota's legacy of engineering vehicles that are built to withstand the test of time and conquer diverse landscapes.", 3444.0, 18.5, 2, 415.0, "https://www.auto-data.net/images/f109/Toyota-Land-Cruiser-J300.jpg", "Toyota", "Land Cruiser", 85000.0, 190.0, null, null, null, 250.0, 650.0, 1, 2520.0, 2003 },
                    { 221, 8.5999999999999996, 5, "Blue", 14, "The BMW E91, introduced in 2005, is a versatile and stylish wagon that embodies BMW's commitment to combining performance, practicality, and dynamic design. With its sleek yet functional design, the E91 carries BMW's iconic styling cues. The balanced proportions, clean lines, and attention to detail create an appearance that is both elegant and athletic. Inside the E91, the cabin offers a harmonious blend of comfort and utility. High-quality materials, ergonomic design, and ample cargo space make it a practical choice for drivers seeking versatility without sacrificing luxury. The driver-centric layout ensures an engaging and intuitive driving experience. Under the hood, the E91 presents a range of engine options, each delivering a balance between power and efficiency. The vehicle's suspension system and responsive steering contribute to a dynamic and enjoyable driving dynamic, whether navigating city streets or highways. While the E91's technology might not be as advanced as that of newer models, it offers essential features to enhance the driving experience, including connectivity and entertainment options. As a part of BMW's lineup, the E91 reflects the brand's dedication to producing vehicles that offer driving pleasure without compromising on functionality. It's a desirable choice for drivers who seek a wagon that delivers both performance and practicality. In conclusion, the 2005 BMW E91 stands as a testament to BMW's commitment to engineering vehicles that offer a blend of performance and versatility. With its sleek design, functional interior, and engaging driving dynamics, the E91 continues to capture the essence of BMW's philosophy of creating vehicles that provide the best of both worlds – style and practicality.", 1995.0, 8.0999999999999996, 1, 163.0, "https://www.auto-data.net/images/f41/BMW-3-Series-Touring-E91.jpg", "BMW", "E91", 8200.0, 140.0, null, null, null, 223.0, 340.0, 2, 1510.0, 2005 },
                    { 222, 6.7999999999999998, 7, "Yellow", 14, "The Dodge Ram, introduced in 2005, is a rugged and capable full-size pickup truck that embodies Dodge's commitment to power, utility, and distinctive design. With its bold and muscular design, the Ram carries Dodge's signature styling cues. The robust grille, chiseled lines, and imposing stance create an appearance that exudes strength and capability. Inside the Ram, the cabin offers a functional and spacious environment. Utilitarian materials, comfortable seating, and a layout designed for practicality make it well-suited for both work and everyday driving. The emphasis on functionality extends to the controls and features, prioritizing ease of use. Under the hood, the Ram presents a range of powerful engine options, delivering impressive towing and hauling capabilities. The truck's sturdy chassis and suspension system contribute to a stable and confident ride, whether carrying heavy loads or navigating rough terrains. While the 2005 Ram's technology might not match the advanced features of modern trucks, it provides essential amenities to enhance both work and leisure, including entertainment and connectivity options. As part of Dodge's lineup, the Ram reflects the brand's reputation for producing vehicles that cater to drivers who demand performance and versatility. It's a sought-after choice for truck enthusiasts and drivers seeking a dependable and robust pickup truck. In conclusion, the 2005 Dodge Ram stands as a testament to Dodge's commitment to engineering trucks that offer power and utility. With its commanding design, practical interior, and robust capabilities, the Ram continues to uphold Dodge's legacy of creating vehicles that can tackle tough tasks and deliver a dependable performance in various scenarios.", 5657.0, 18.100000000000001, 2, 345.0, "https://www.auto-data.net/images/f46/Dodge-Ram-1500-III-DR-DH.jpg", "Dodge", "Ram", 3700.0, 330.0, null, null, null, 250.0, 529.0, 1, 1880.0, 2005 },
                    { 223, 11.1, 4, "Red", 21, "The Dacia Sandero II Stepway, introduced in 2013, is a practical and affordable compact crossover that embodies Dacia's commitment to simplicity, value, and functionality. With its rugged and utilitarian design, the Sandero II Stepway carries Dacia's straightforward styling cues. The elevated ground clearance, protective cladding, and distinctive front grille create an appearance that balances practicality and adventure. Inside the Sandero II Stepway, the cabin offers a straightforward and functional layout. Basic yet durable materials, ergonomic seating, and practical storage solutions make it well-suited for drivers seeking a no-frills approach to driving. Under the hood, the Sandero II Stepway presents efficient engine options, delivering dependable performance for everyday commuting and urban driving. The crossover's slightly raised suspension system provides enhanced ground clearance and a comfortable ride, suitable for varied road conditions. While the 2013 Sandero II Stepway's technology might not be as advanced as that of modern crossovers, it offers essential features to enhance the driving experience, focusing on practicality rather than luxury. As part of Dacia's lineup, the Sandero II Stepway reflects the brand's reputation for producing vehicles that prioritize value and functionality. It's a practical choice for drivers seeking a budget-friendly crossover that meets basic transportation needs. In conclusion, the 2013 Dacia Sandero II Stepway stands as a testament to Dacia's philosophy of providing affordable and straightforward vehicles. With its rugged design, functional interior, and dependable performance, the Sandero II Stepway continues to uphold Dacia's legacy of creating vehicles that offer practicality and value for budget-conscious drivers.", 2999.0, 6.7000000000000002, 2, 90.0, "https://cdn3.focus.bg/autodata/i/dacia/sandero/sandero-ii-stepway/large/675829b961ab0a61241270896e202b87.jpg", "Dacia", "Sandero II Stepway", 9999.0, 199.0, null, null, null, 170.0, 135.0, 2, 1023.0, 2013 },
                    { 224, 10.800000000000001, 3, "Black", 14, "The Mercedes-Benz A-Class (W168), introduced in 1999, is a compact car that embodies Mercedes-Benz's commitment to innovation, versatility, and safety. With its distinctive design, the A-Class (W168) showcases Mercedes-Benz's approach to creating compact vehicles that offer practicality without sacrificing style. The unique tall body design and compact dimensions create an appearance that maximizes interior space while remaining compact and agile. Inside the A-Class (W168), the cabin offers a surprisingly roomy and flexible environment. Smart space utilization, ergonomic seating, and practical storage solutions make it suitable for both urban driving and longer journeys. The driver-centric layout reflects Mercedes-Benz's dedication to creating user-friendly interiors. Under the hood, the A-Class (W168) presents a range of engine options, delivering efficient performance for various driving scenarios. The vehicle's suspension system provides a balanced and comfortable ride, suitable for navigating city streets and highways. While the 1999 A-Class (W168) might not feature the same level of technology as more recent Mercedes-Benz models, it offers essential amenities to enhance the driving experience, focusing on comfort and convenience. As part of Mercedes-Benz's lineup, the A-Class (W168) reflects the brand's commitment to engineering vehicles that cater to diverse driver needs. It's a practical choice for drivers seeking a compact car that offers Mercedes-Benz's reputation for quality and safety. In conclusion, the 1999 Mercedes-Benz A-Class (W168) stands as a testament to Mercedes-Benz's philosophy of creating vehicles that combine innovation and functionality. With its distinctive design, versatile interior, and emphasis on safety, the A-Class (W168) continues to capture the essence of Mercedes-Benz's dedication to producing vehicles that adapt to the evolving needs of drivers.", 1598.0, 10.199999999999999, 2, 102.0, "https://static-eu.cargurus.com/images/forsale/2023/05/16/15/02/2003_mercedes-benz_a-class-pic-3974413017599453644-1024x768.jpeg", "Mercedes-Benz", "A-Class (W168)", 4400.0, 110.0, null, null, null, 180.0, 150.0, 2, 1135.0, 1999 },
                    { 225, 8.0999999999999996, 1, "Grey", 14, "The Audi A4, introduced in 2011, represents Audi's commitment to luxury, performance, and innovative design. With a sleek and modern exterior, the A4 boasts Audi's signature aesthetic, characterized by clean lines, a distinctive grille, and balanced proportions. Inside the cabin, high-quality materials, meticulous craftsmanship, and advanced technology come together to create a refined and comfortable environment. The A4 offers a range of engine options that balance power and efficiency, while its suspension and steering provide a dynamic driving experience. Equipped with advanced safety and technology features like adaptive cruise control, automatic emergency braking, and lane departure warning, the 2011 A4 prioritizes driver confidence and occupant protection. As a part of Audi's lineup, the A4 embodies the brand's commitment to luxury and engineering excellence. It remains a sought-after choice for those seeking a compact luxury sedan that marries style, performance, and technological innovation seamlessly.", 1798.0, 7.4000000000000004, 2, 170.0, "https://www.auto-data.net/images/f93/Audi-A4-B8-8K-facelift-2011.jpg", "Audi", "A4", 12400.0, 180.0, null, null, null, 230.0, 320.0, 2, 1430.0, 2011 },
                    { 226, 3.6000000000000001, 1, "Black", 14, "The Porsche Panamera G2, introduced in 2019, is a luxury sports sedan that showcases Porsche's dedication to performance, innovation, and refined design. With its sleek and athletic design, the Panamera G2 embodies Porsche's iconic styling cues. The sweeping lines, distinctive headlights, and wide stance create an appearance that seamlessly combines elegance with sportiness. Inside the Panamera G2, the cabin offers a luxurious and driver-focused environment. High-quality materials, meticulous attention to detail, and cutting-edge technology create an interior that caters to both driver and passenger satisfaction. The intuitive infotainment system and driver assistance features enhance the driving experience. Under the hood, the Panamera G2 presents a range of powerful engine options, delivering exhilarating acceleration and impressive handling characteristics. The sedan's advanced suspension system and responsive steering contribute to a dynamic and engaging driving experience. In terms of safety and technology, the 2019 Panamera G2 is equipped with a suite of advanced features, including adaptive cruise control, lane keeping assist, and automatic emergency braking. These systems work together to enhance driver confidence and occupant protection. As part of Porsche's lineup, the Panamera G2 reflects the brand's commitment to engineering excellence and driving pleasure. It's a coveted choice for drivers seeking a luxury sports sedan that offers a blend of style, performance, and cutting-edge technology. In conclusion, the 2019 Porsche Panamera G2 stands as a testament to Porsche's philosophy of creating vehicles that deliver both luxury and performance. With its striking design, opulent interior, and advanced safety and technology features, the Panamera G2 continues to capture the essence of Porsche's dedication to providing an exceptional driving experience.", 3996.0, 14.4, 2, 550.0, "https://www.auto-data.net/images/f15/file8561600.jpg", "Porsche", "Panamera G2", 175000.0, 100.0, null, null, null, 306.0, 770.0, 1, 1995.0, 2019 },
                    { 227, 4.4000000000000004, 2, "Black", 21, "The BMW E92 M3 is a high-performance sports coupe known for its powerful V8 engine, precise handling, and iconic design. With a perfect blend of luxury and exhilaration, it remains a favorite among car enthusiasts seeking a thrilling driving experience.", 4361.0, 18.5, 2, 450.0, "https://pbs.twimg.com/media/Ei3lNlHXsAAoMQD.jpg", "BMW", "E92 M3", 66500.0, 600.0, null, null, null, 250.0, 440.0, 1, 1530.0, 2010 },
                    { 228, 3.6000000000000001, 2, "Black", 21, "The Mercedes CLS 63 AMG is a luxury four-door coupe that combines elegance with blistering performance. Powered by a potent V8 engine, it offers a comfortable yet exhilarating driving experience, setting new standards for high-end performance cars.", 5461.0, 14.4, 2, 585.0, "https://citycarrentals.ca/wp-content/uploads/2018/02/mercedes-benz-cls-63-amg-black-3.jpg", "Mercedes-Benz", "CLS 63 AMG", 67500.0, 680.0, null, null, null, 250.0, 800.0, 1, 1945.0, 2014 },
                    { 229, 5.0999999999999996, 2, "Black", 21, "The Audi S5 is a dynamic and sleek sports coupe, featuring a turbocharged V6 engine and Quattro all-wheel drive. Its blend of performance, comfort, and cutting-edge technology make it a compelling choice for driving enthusiasts with a taste for luxury.", 2999.0, 10.699999999999999, 2, 333.0, "https://i.pinimg.com/originals/4f/23/28/4f2328613a9577fef6f77eee198e5f65.jpg", "Audi", "S5", 64000.0, 510.0, null, null, null, 250.0, 440.0, 1, 1745.0, 2012 },
                    { 230, 1.1000000000000001, 1, "Black", 21, "TestDesc1", 444.0, 11.0, 1, 333.0, "https://images.drive.com.au/driveau/image/upload/t_wp-default/v1/cms/uploads/jjslyagf8e3gcny2doyy", "TestMake1", "TestModel1", 1234.0, 111.0, null, null, null, 123.0, 333.0, 1, 1234.0, 2011 }
                });
        }
    }
}
